export default {
    translations: {
        fr: {
            Actions: "Actions",
            All: "Tout",
            Archives: "Archives",
            B: "o",
            Back: "Retour",
            CB: "Presse-papiers",
            Cancel: "Annuler",
            Clear_Clipboard: "Vider le presse-papiers",
            Clear_Clipboard_Confirm:
                "Êtes-vous sûr de vouloir vider le presse-papiers ?",
            Confirm_Folder_del:
                "Êtes-vous sûr de vouloir supprimer le dossier ainsi que tous ses éléments ?",
            Confirm_del: "Êtes-vous sûr de vouloir effacer ce fichier ?",
            Copy: "Copier",
            Copy_Cut_Count_Limit:
                "Vous avez sélectionné trop de fichiers / dossiers pour: msg_sub_action. Limite:: copy_cut_max_count fichiers / opération",
            Copy_Cut_Not_Allowed:
                "Vous n'êtes pas autorisé à :size des :folders.",
            Copy_Cut_Size_Limit:
                "Les fichiers/dossiers sélectionnés sont trop gros pour %1$s. Limite: %2$d MB/opération",
            Cut: "Couper",
            Date: "Date",
            Date_type: "j/m/A",
            Deselect_All: "Tout déselectionner",
            Dimension: "Dimension",
            Dir_No_Write:
                "Le répertoire que vous avez sélectionné n'est pas accessible en écriture.",
            Download: "Télécharger",
            Duplicate: "Dupliquer",
            Edit: "Editer",
            Edit_File: "Editer le contenu du fichier",
            Edit_image: "Editer l'image",
            Empty_name: "Le nom est vide",
            Erase: "Effacer",
            Error_Upload: "Votre fichier dépasse la taille maximum autorisée.",
            Error_extension: "Extension de fichier non autorisée.",
            Existing_Folder: "Dossier existant",
            Extract: "Extraire ici",
            File_Not_Found: "Le fichier est introuvable.",
            File_Open_Edit_Not_Allowed:
                "Vous ne disposez pas des autorisations sur le fichier :sub_action.",
            File_Permission: "Permission du fichier",
            File_Permission_Not_Allowed:
                "Le changement de permission :folder n'est pas autorisé.",
            File_Permission_Recursive: "Appliquez recursivement ?",
            File_Permission_Wrong_Mode:
                "Les permissions saisies sont incorrectes.",
            File_Save_Error:
                "Une erreur s'est produite lors de l'enregistrement du fichier.",
            File_Save_OK: "Fichier enregistré avec succès.",
            File_info: "Information",
            Filename: "Nom",
            Files: "Fichiers",
            Files_ON_Clipboard: "Le presse-papiers contient des fichiers.",
            Filters: "Filtrer",
            Folder_Created: "Dossier correctement créé",
            Folders: "Dossiers",
            Function_Disabled:
                "La fonction :function a été désactivée sur le serveur.",
            GB: "Go",
            Group: "Groupe",
            Image_Editor_Exit: "Sortie",
            Image_Editor_No_Save: "Impossible d'enregistrer l'image",
            Image_Editor_Save: "Sauvegarder",
            Images: "Images",
            Insert_Folder_Name: "Insérer le nom du dossier :",
            KB: "Ko",
            Lang_Change: "Changer la langue",
            Lang_Not_Found: "Le fichier de langue est introuvable.",
            MB: "Mo",
            Music: "Musique",
            New_File: "Nouveau fichier",
            New_Folder: "Nouveau dossier",
            No: "Non",
            No_Extension: "Vous devez ajouter une extension au fichier.",
            "Not enough Memory": "Mémoire insuffisante",
            OK: "OK",
            Open: "Ouvrir",
            Operations: "Opérations",
            Paste: "Coller",
            Paste_Confirm:
                "Êtes-vous sûr de vouloir coller dans ce répertoire ? Cette action remplacera les fichiers/dossiers déjà existants.",
            Paste_Failed: "Impossible de coller les fichier(s)",
            Paste_Here: "Coller dans ce dossier",
            Preview: "Aperçu",
            Rename: "Renommer",
            Rename_existing_file: "Ce fichier existe déjà",
            Rename_existing_folder: "Ce dossier existe déjà",
            Return_Files_List: "Revenir à la liste des fichiers",
            Root: "Racine",
            "SERVER ERROR": "ERREUR SERVEUR",
            Select: "Sélectionner",
            Select_All: "Tout selectionner",
            Show_url: "Afficher l'URL",
            Size: "Taille",
            Sorting: "Trier",
            Swipe_help:
                "Glissez le nom du fichier/dossier pour afficher les options",
            TB: "To",
            Text_filter: "Texte de filtrage",
            Toolbar: "Barre d'outils",
            Type: "Type",
            Type_dir: "Dossier",
            Upload_add_files: "Ajouter des fichiers",
            Upload_base: "Téléchargement classique",
            Upload_base_help:
                'Glisser-Déposer des fichiers (navigateurs récents) ou cliquer sur le bontons en haut pour ajouter des fichiers. Cliquer sur "Envoyer les fichiers". Lorsque le chargement est complet, cliquer sur "Revenir à la liste des fichiers".',
            Upload_error_messages: {
                "1":
                    "La taille du fichier dépasse la limite fixée par le paramètre upload_max_filesize dans php.ini",
                "2":
                    "La taille du fichier dépasse la limite fixée par le paramètre MAX_FILE_SIZE du formulaire",
                "3": "Le fichier n'a pas été correctement téléchargé",
                "4": "Aucun fichier n'a pas été téléchargé",
                "6": "Il manque le répertoire temporaire",
                "7": "Impossible d'écrire le fichier sur le disque",
                "8": "Une extension PHP a bloqué le téléchargement",
                abort: "Téléchargement des fichiers annulé",
                accept_file_types: "Ce type de fichier n'est pas accepté",
                image_resize: "Impossible de redimensionner l'image",
                max_file_size: "La taille du fichier est trop importante",
                max_height:
                    "La hauteur de l'image est supérieure à la limite maximum autorisée",
                max_number_of_files:
                    "Le nombre de fichiers à télécharger est trop important",
                max_width:
                    "La largeur de l'image est supérieure à la limite maximum autorisée",
                min_file_size: "La taille du fichier est trop faible",
                min_height:
                    "La hauteur de l'image est inférieure à la limite minimum autorisée",
                min_width:
                    "La largeur de l'image est inférieure à la limite minimum autorisée",
                post_max_size:
                    "Le fichier téléchargé dépasse la directive post_max_size dans php.ini"
            },
            Upload_file: "Envoyer un fichier",
            Upload_message: "Glissez les fichiers ici pour les ajouter",
            Upload_start: "Envoyer les fichiers",
            Upload_url: "Depuis une URL",
            User: "Utilisateur",
            Valid_Extensions: "Extensions valides: :editable_text_file_exts",
            Videos: "Vidéos",
            View: "Vue",
            View_boxes: "Vue par icônes",
            View_columns_list: "Vue par listes de colonne",
            View_list: "Vue par liste",
            Yes: "Oui",
            Zip_Invalid:
                "Cette extension n'est pas supportée. Extensions valides: zip, gz, tar.",
            Zip_No_Extract:
                "Extraction impossible. Le fichier est peut-être corrompu.",
            forbidden: "Interdit",
            ftp_cant_chmod:
                "Impossible de changer les droits de fichier de façon Unix (chmod) sur un serveur FTP Windows",
            ftp_delete_failure: "Can't remove non empty folder",
            ftp_failure: "Something gone wrong with ftp server",
            max_size_reached:
                "Votre répertoire d'image a déjà atteind sa taille maximale de :size mo.",
            "no action passed": "Aucune action demandée",
            "no file": "Fichier manquant",
            "no path": "Chemin manquant",
            "total size": "Taille totale",
            "view type number missing": "Type de vue manquant",
            "wrong action": "Action invalide",
            "wrong data": "Données invalides",
            "wrong extension": "Extension invalide",
            "wrong name": "Nom invalide",
            "wrong option": "Mauvaise option",
            "wrong path": "Mauvais chemin",
            "wrong sub-action": "Mauvaise sous-action"
        }
    },
    config: {
        version: "9.14.0",
        laravel_route_prefix: "/filemanager",
        base_url: "http://",
        upload_dir: "/uploads/files/",
        current_path: "uploads/files/",
        thumbs_base_path: "thumbs/",
        thumbs_upload_dir: "/thumbs/",
        mime_extension_rename: true,
        ftp_host: false,
        ftp_user: "user",
        ftp_pass: "pass",
        ftp_base_folder: "base_folder",
        ftp_temp_folder: "../temp/",
        ftp_thumbs_dir: "/thumbs/",
        ftp_ssl: false,
        ftp_port: 21,
        multiple_selection: true,
        multiple_selection_action_button: true,
        access_keys: [
            "bde8a28b709b180ba02826e4701c975fc943e5ef511bf78a713146a558ff93e3"
        ],
        MaxSizeTotal: false,
        MaxSizeUpload: 10,
        filePermission: 493,
        folderPermission: 511,
        default_language: false,
        icon_theme: "ico",
        show_total_size: false,
        show_folder_size: false,
        show_sorting_bar: true,
        show_filter_buttons: true,
        show_language_selection: true,
        transliteration: false,
        convert_spaces: false,
        replace_with: "_",
        lower_case: false,
        add_time_to_img: false,
        image_max_width: 0,
        image_max_height: 0,
        image_max_mode: "auto",
        image_resizing: false,
        image_resizing_width: 0,
        image_resizing_height: 0,
        image_resizing_mode: "auto",
        image_resizing_override: false,
        image_watermark: false,
        image_watermark_position: "br",
        image_watermark_padding: 10,
        default_view: 0,
        ellipsis_title_after_first_row: true,
        delete_files: true,
        create_folders: true,
        delete_folders: true,
        upload_files: true,
        rename_files: true,
        rename_folders: true,
        duplicate_files: true,
        extract_files: true,
        copy_cut_files: true,
        copy_cut_dirs: true,
        chmod_files: true,
        chmod_dirs: true,
        preview_text_files: true,
        edit_text_files: true,
        create_text_files: true,
        download_files: true,
        previewable_text_file_exts: [
            "bsh",
            "c",
            "css",
            "cc",
            "cpp",
            "cs",
            "csh",
            "cyc",
            "cv",
            "htm",
            "html",
            "java",
            "js",
            "m",
            "mxml",
            "perl",
            "pl",
            "pm",
            "py",
            "rb",
            "sh",
            "xhtml",
            "xml",
            "xsl",
            "txt",
            "log",
            ""
        ],
        editable_text_file_exts: [
            "txt",
            "log",
            "xml",
            "html",
            "css",
            "htm",
            "js",
            ""
        ],
        jplayer_exts: [
            "mp4",
            "flv",
            "webmv",
            "webma",
            "webm",
            "m4a",
            "m4v",
            "ogv",
            "oga",
            "mp3",
            "midi",
            "mid",
            "ogg",
            "wav"
        ],
        cad_exts: [
            "dwg",
            "dxf",
            "hpgl",
            "plt",
            "spl",
            "step",
            "stp",
            "iges",
            "igs",
            "sat",
            "cgm",
            "svg"
        ],
        googledoc_enabled: true,
        googledoc_file_exts: [
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "pdf",
            "odt",
            "odp",
            "ods"
        ],
        copy_cut_max_size: 100,
        copy_cut_max_count: 200,
        ext_img: ["jpg", "jpeg", "png", "gif", "bmp", "svg", "ico"],
        ext_file: [
            "doc",
            "docx",
            "rtf",
            "pdf",
            "xls",
            "xlsx",
            "txt",
            "csv",
            "html",
            "xhtml",
            "psd",
            "sql",
            "log",
            "fla",
            "xml",
            "ade",
            "adp",
            "mdb",
            "accdb",
            "ppt",
            "pptx",
            "odt",
            "ots",
            "ott",
            "odb",
            "odg",
            "otp",
            "otg",
            "odf",
            "ods",
            "odp",
            "css",
            "ai",
            "kmz",
            "dwg",
            "dxf",
            "hpgl",
            "plt",
            "spl",
            "step",
            "stp",
            "iges",
            "igs",
            "sat",
            "cgm",
            "tiff",
            ""
        ],
        ext_video: [
            "mov",
            "mpeg",
            "m4v",
            "mp4",
            "avi",
            "mpg",
            "wma",
            "flv",
            "webm"
        ],
        ext_music: ["mp3", "mpga", "m4a", "ac3", "aiff", "mid", "ogg", "wav"],
        ext_misc: ["zip", "rar", "gz", "tar", "iso", "dmg"],
        ext_blacklist: false,
        empty_filename: false,
        files_without_extension: false,
        tui_active: true,
        tui_position: "bottom",
        "common.backgroundImage": "none",
        "common.backgroundColor": "#ececec",
        "common.border": "1px solid #E6E7E8",
        "header.backgroundImage": "none",
        "header.backgroundColor": "#ececec",
        "header.border": "0px",
        "menu.normalIcon.path": "/vendor/responsivefilemanager/svg/icon-d.svg",
        "menu.normalIcon.name": "icon-d",
        "menu.activeIcon.path": "/vendor/responsivefilemanager/svg/icon-b.svg",
        "menu.activeIcon.name": "icon-b",
        "menu.disabledIcon.path":
            "/vendor/responsivefilemanager/svg/icon-a.svg",
        "menu.disabledIcon.name": "icon-a",
        "menu.hoverIcon.path": "/vendor/responsivefilemanager/svg/icon-c.svg",
        "menu.hoverIcon.name": "icon-c",
        "menu.iconSize.width": "24px",
        "menu.iconSize.height": "24px",
        "submenu.backgroundColor": "#ececec",
        "submenu.partition.color": "#000000",
        "submenu.normalIcon.path":
            "/vendor/responsivefilemanager/svg/icon-d.svg",
        "submenu.normalIcon.name": "icon-d",
        "submenu.activeIcon.path":
            "/vendor/responsivefilemanager/svg/icon-b.svg",
        "submenu.activeIcon.name": "icon-b",
        "submenu.iconSize.width": "32px",
        "submenu.iconSize.height": "32px",
        "submenu.normalLabel.color": "#000",
        "submenu.normalLabel.fontWeight": "normal",
        "submenu.activeLabel.color": "#000",
        "submenu.activeLabel.fontWeight": "normal",
        "checkbox.border": "1px solid #E6E7E8",
        "checkbox.backgroundColor": "#000",
        "range.pointer.color": "#333",
        "range.bar.color": "#ccc",
        "range.subbar.color": "#606060",
        "range.disabledPointer.color": "#d3d3d3",
        "range.disabledBar.color": "rgba(85,85,85,0.06)",
        "range.disabledSubbar.color": "rgba(51,51,51,0.2)",
        "range.value.color": "#000",
        "range.value.fontWeight": "normal",
        "range.value.fontSize": "11px",
        "range.value.border": "0",
        "range.value.backgroundColor": "#f5f5f5",
        "range.title.color": "#000",
        "range.title.fontWeight": "lighter",
        "colorpicker.button.border": "0px",
        "colorpicker.title.color": "#000",
        file_number_limit_js: 500,
        hidden_folders: [],
        hidden_files: ["config.php"],
        url_upload: true,
        fixed_image_creation: false,
        fixed_path_from_filemanager: ["../test/", "../test1/"],
        fixed_image_creation_name_to_prepend: ["", "test_"],
        fixed_image_creation_to_append: ["_test", ""],
        fixed_image_creation_width: [300, 400],
        fixed_image_creation_height: [200, 300],
        fixed_image_creation_option: ["crop", "auto"],
        relative_image_creation: false,
        relative_path_from_current_pos: ["./", "./"],
        relative_image_creation_name_to_prepend: ["", ""],
        relative_image_creation_name_to_append: ["_thumb", "_thumb1"],
        relative_image_creation_width: [300, 400],
        relative_image_creation_height: [200, 300],
        relative_image_creation_option: ["crop", "crop"],
        remember_text_filter: false,
        ext: [
            "jpg",
            "jpeg",
            "png",
            "gif",
            "bmp",
            "svg",
            "ico",
            "doc",
            "docx",
            "rtf",
            "pdf",
            "xls",
            "xlsx",
            "txt",
            "csv",
            "html",
            "xhtml",
            "psd",
            "sql",
            "log",
            "fla",
            "xml",
            "ade",
            "adp",
            "mdb",
            "accdb",
            "ppt",
            "pptx",
            "odt",
            "ots",
            "ott",
            "odb",
            "odg",
            "otp",
            "otg",
            "odf",
            "ods",
            "odp",
            "css",
            "ai",
            "kmz",
            "dwg",
            "dxf",
            "hpgl",
            "plt",
            "spl",
            "step",
            "stp",
            "iges",
            "igs",
            "sat",
            "cgm",
            "tiff",
            "",
            "zip",
            "rar",
            "gz",
            "tar",
            "iso",
            "dmg",
            "mov",
            "mpeg",
            "m4v",
            "mp4",
            "avi",
            "mpg",
            "wma",
            "flv",
            "webm",
            "mp3",
            "mpga",
            "m4a",
            "ac3",
            "aiff",
            "mid",
            "ogg",
            "wav"
        ],
        tui_defaults_config: {
            "common.backgroundImage": "none",
            "common.backgroundColor": "#ececec",
            "common.border": "1px solid #E6E7E8",
            "header.backgroundImage": "none",
            "header.backgroundColor": "#ececec",
            "header.border": "0px",
            "menu.normalIcon.path":
                "/vendor/responsivefilemanager/svg/icon-d.svg",
            "menu.normalIcon.name": "icon-d",
            "menu.activeIcon.path":
                "/vendor/responsivefilemanager/svg/icon-b.svg",
            "menu.activeIcon.name": "icon-b",
            "menu.disabledIcon.path":
                "/vendor/responsivefilemanager/svg/icon-a.svg",
            "menu.disabledIcon.name": "icon-a",
            "menu.hoverIcon.path":
                "/vendor/responsivefilemanager/svg/icon-c.svg",
            "menu.hoverIcon.name": "icon-c",
            "menu.iconSize.width": "24px",
            "menu.iconSize.height": "24px",
            "submenu.backgroundColor": "#ececec",
            "submenu.partition.color": "#000000",
            "submenu.normalIcon.path":
                "/vendor/responsivefilemanager/svg/icon-d.svg",
            "submenu.normalIcon.name": "icon-d",
            "submenu.activeIcon.path":
                "/vendor/responsivefilemanager/svg/icon-b.svg",
            "submenu.activeIcon.name": "icon-b",
            "submenu.iconSize.width": "32px",
            "submenu.iconSize.height": "32px",
            "submenu.normalLabel.color": "#000",
            "submenu.normalLabel.fontWeight": "normal",
            "submenu.activeLabel.color": "#000",
            "checkbox.border": "1px solid #E6E7E8",
            "checkbox.backgroundColor": "#000",
            "range.pointer.color": "#333",
            "range.bar.color": "#ccc",
            "range.subbar.color": "#606060",
            "range.disabledPointer.color": "#d3d3d3",
            "range.disabledBar.color": "rgba(85,85,85,0.06)",
            "range.disabledSubbar.color": "rgba(51,51,51,0.2)",
            "range.value.color": "#000",
            "range.value.fontWeight": "normal",
            "range.value.fontSize": "11px",
            "range.value.border": "0",
            "range.value.backgroundColor": "#f5f5f5",
            "range.title.color": "#000",
            "range.title.fontWeight": "lighter",
            "colorpicker.button.border": "0px",
            "colorpicker.title.color": "#000"
        }
    },
    vars: {
        add_time_to_img: 0,
        apply_type: "apply_link",
        apply: "apply_link",
        callback: 0,
        chmod_dirs_allowed: 1,
        chmod_files_allowed: 1,
        class_ext: "",
        clipboard: 0,
        convert_spaces: false,
        copy_cut_dirs_allowed: 1,
        copy_cut_files_allowed: 1,
        copy_cut_max_count: 200,
        copy_cut_max_size: 100,
        crossdomain: false,
        cur_dir_thumb: "/thumbs/qsdqsd/",
        cur_dir: "/uploads/files/qsdqsd/",
        current_files_number: 0,
        current_folders_number: 0,
        current_url:
            "http:///filemanager?editor=tinymce&amp;type=2&amp;lang=fr_FR&amp;popup=0&amp;crossdomain=0&amp;relative_url=0&amp;akey=bde8a28b709b180ba02826e4701c975fc943e5ef511bf78a713146a558ff93e3&amp;fldr=qsdqsd&amp;5d777bc76fe1d",
        descending: 1,
        duplicate: 1,
        edit_text_files_allowed: 1,
        editor: "tinymce",
        extensions: null,
        extract_files_allowed: 1,
        field_id: "",
        file_number_limit_js: 500,
        fileCurrentNum: null,
        files: [{ file: ".." }],
        fldr_value: "qsdqsd/",
        filter: "",
        foldersCurrentCount: null,
        ftp: null,
        get_params: {
            editor: "tinymce",
            type: "2",
            lang: "fr_FR",
            popup: false,
            crossdomain: false,
            extensions: null,
            field_id: "",
            multiple: null,
            relative_url: 0,
            akey:
                "bde8a28b709b180ba02826e4701c975fc943e5ef511bf78a713146a558ff93e3",
            fldr: ""
        },
        lower_case: false,
        multiple: null,
        n_files: 2,
        parent: "qsdqsd/",
        popup: false,
        replace_with: "_",
        return_relative_url: 0,
        rfm_subfolder: "",
        show_folder_size: 0,
        sizeCurrentFolder: null,
        sort_by: "name",
        src: "",
        subdir_path: "qsdqsd",
        subdir: "qsdqsd/",
        thumbs_path: "thumbs/qsdqsd/",
        transliteration: false,
        type_param: "2",
        upload_dir: "/uploads/files/",
        uploadFolderError: false,
        vendor_path: "/vendor/responsivefilemanager/",
        view: 0
    }
};
